import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {GET_ALL_CLIENTS, CLIENT_BY_SLUG} from "../graphql/CLIENT_QUERIES";
import {useLazyQuery, useQuery} from "@apollo/client";

export default function Home() {

    const {data, loading} = useQuery(GET_ALL_CLIENTS)

    const [loadPostBySlug, {data: clientBySlug, loading: slugLoading}] = useLazyQuery(CLIENT_BY_SLUG)

    const fetchPostBySlug = async (slug) => {

        await loadPostBySlug({
            variables: {
                slug: slug
            }
        })

    }
    if (loading || slugLoading) {
       return(
           <main className={styles.main}>
               <p>Loading</p>
           </main>
       )
    }

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Contentfull data test
                </h1>
                {data.clientsCollection.items.map((item, idx) => {
                    return <div key={idx} className="box" onClick={e => fetchPostBySlug(item.slug)}>
                        <h2>{item.title}</h2>
                        <p>{item.subtitle}</p>
                    </div>
                })}

                <div>
                    <p>Selected data</p>
                    <pre>
                        {JSON.stringify(clientBySlug, null,2)}
                    </pre>
                </div>
            </main>
        </div>
    )
}