import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { getAllPosts } from '../utils/contentfull';

export default function Home({posts}) {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Contentfull data test
        </h1>

        <div className={styles.grid}>
          {posts.map((post) => (
            <a href="https://nextjs.org/docs" className={styles.card}>
              <h2>{post.title}</h2>
              <p>{post.subtitle}</p>
            </a>
          ))}
        </div>
      </main>
    </div>
  )
}

export async function getStaticProps() {
  const posts = await getAllPosts();
  return {
    props: {
      posts,
    },
  };
}